package main

import (
	"bufio"
	"fmt"
	"os"
	"regexp"
	"strings"
)

// ValidCommitTypes lists all allowed conventional commit types
var ValidCommitTypes = []string{
	"feat",     // A new feature
	"fix",      // A bug fix
	"docs",     // Documentation only changes
	"style",    // Changes that don't affect code meaning (formatting, whitespace)
	"refactor", // Code change that neither fixes a bug nor adds a feature
	"perf",     // Code change that improves performance
	"test",     // Adding missing tests or correcting existing tests
	"build",    // Changes that affect the build system or dependencies
	"ci",       // Changes to CI configuration files and scripts
	"chore",    // Other changes that don't modify src or test files
	"revert",   // Reverts a previous commit
}

// conventionalCommitPattern matches: type(scope): description or type: description
// Type must be lowercase, scope is optional and must be lowercase alphanumeric with hyphens/underscores
var conventionalCommitPattern = regexp.MustCompile(
	`^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([a-z0-9_-]+\))?: .+`,
)

// mergeCommitPattern matches merge commits generated by git
var mergeCommitPattern = regexp.MustCompile(`^Merge `)

// revertCommitPattern matches revert commits generated by git
var revertCommitPattern = regexp.MustCompile(`^Revert "`)

// ValidationError represents a commit message validation error
type ValidationError struct {
	Message     string
	FirstLine   string
	Suggestion  string
}

func (e *ValidationError) Error() string {
	var sb strings.Builder

	sb.WriteString("\n")
	sb.WriteString("==========================================\n")
	sb.WriteString("COMMIT REJECTED: Invalid commit message format!\n")
	sb.WriteString("==========================================\n")
	sb.WriteString("\n")
	sb.WriteString(fmt.Sprintf("Your commit message:\n  \"%s\"\n\n", e.FirstLine))
	sb.WriteString("Conventional Commits format required:\n")
	sb.WriteString("  <type>[optional scope]: <description>\n\n")
	sb.WriteString("Allowed types:\n")
	sb.WriteString("  feat     - A new feature\n")
	sb.WriteString("  fix      - A bug fix\n")
	sb.WriteString("  docs     - Documentation only changes\n")
	sb.WriteString("  style    - Formatting, whitespace (no code change)\n")
	sb.WriteString("  refactor - Code change (no feature or fix)\n")
	sb.WriteString("  perf     - Performance improvement\n")
	sb.WriteString("  test     - Adding or correcting tests\n")
	sb.WriteString("  build    - Build system or dependencies\n")
	sb.WriteString("  ci       - CI configuration changes\n")
	sb.WriteString("  chore    - Other maintenance tasks\n")
	sb.WriteString("  revert   - Reverts a previous commit\n")
	sb.WriteString("\n")
	sb.WriteString("Examples:\n")
	sb.WriteString("  feat: add transaction export feature\n")
	sb.WriteString("  fix(parser): handle negative amounts correctly\n")
	sb.WriteString("  docs: update README with installation steps\n")
	sb.WriteString("  test(handlers): add dashboard endpoint tests\n")
	sb.WriteString("\n")

	return sb.String()
}

// ValidateCommitMessage validates a commit message string against conventional commits format
func ValidateCommitMessage(message string) error {
	message = strings.TrimSpace(message)
	if message == "" {
		return &ValidationError{
			Message:   "Empty commit message",
			FirstLine: "",
		}
	}

	// Get first line
	firstLine := strings.Split(message, "\n")[0]
	firstLine = strings.TrimSpace(firstLine)

	// Skip merge commits
	if mergeCommitPattern.MatchString(firstLine) {
		return nil
	}

	// Skip revert commits (generated by git revert)
	if revertCommitPattern.MatchString(firstLine) {
		return nil
	}

	// Validate against conventional commit pattern
	if !conventionalCommitPattern.MatchString(firstLine) {
		return &ValidationError{
			Message:   "Invalid conventional commit format",
			FirstLine: firstLine,
		}
	}

	return nil
}

// ValidateCommitMessageFile validates a commit message from a file (used by git hooks)
func ValidateCommitMessageFile(filePath string) error {
	file, err := os.Open(filePath)
	if err != nil {
		return fmt.Errorf("failed to open commit message file: %w", err)
	}
	defer file.Close()

	var lines []string
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := scanner.Text()
		// Skip comment lines (git adds these)
		if !strings.HasPrefix(line, "#") {
			lines = append(lines, line)
		}
	}

	if err := scanner.Err(); err != nil {
		return fmt.Errorf("failed to read commit message file: %w", err)
	}

	message := strings.Join(lines, "\n")
	return ValidateCommitMessage(message)
}

// IsValidCommitType checks if a type is a valid conventional commit type
func IsValidCommitType(commitType string) bool {
	for _, validType := range ValidCommitTypes {
		if commitType == validType {
			return true
		}
	}
	return false
}
