// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.countAllTransactionsStmt, err = db.PrepareContext(ctx, countAllTransactions); err != nil {
		return nil, fmt.Errorf("error preparing query CountAllTransactions: %w", err)
	}
	if q.countTransactionsByYearStmt, err = db.PrepareContext(ctx, countTransactionsByYear); err != nil {
		return nil, fmt.Errorf("error preparing query CountTransactionsByYear: %w", err)
	}
	if q.createTransactionStmt, err = db.PrepareContext(ctx, createTransaction); err != nil {
		return nil, fmt.Errorf("error preparing query CreateTransaction: %w", err)
	}
	if q.deleteTransactionStmt, err = db.PrepareContext(ctx, deleteTransaction); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteTransaction: %w", err)
	}
	if q.getCategoryByNameStmt, err = db.PrepareContext(ctx, getCategoryByName); err != nil {
		return nil, fmt.Errorf("error preparing query GetCategoryByName: %w", err)
	}
	if q.getCategoryTotalsByYearStmt, err = db.PrepareContext(ctx, getCategoryTotalsByYear); err != nil {
		return nil, fmt.Errorf("error preparing query GetCategoryTotalsByYear: %w", err)
	}
	if q.getDistinctTransactionYearsStmt, err = db.PrepareContext(ctx, getDistinctTransactionYears); err != nil {
		return nil, fmt.Errorf("error preparing query GetDistinctTransactionYears: %w", err)
	}
	if q.getMonthlyTotalsByYearStmt, err = db.PrepareContext(ctx, getMonthlyTotalsByYear); err != nil {
		return nil, fmt.Errorf("error preparing query GetMonthlyTotalsByYear: %w", err)
	}
	if q.getUserStmt, err = db.PrepareContext(ctx, getUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetUser: %w", err)
	}
	if q.listCategoriesStmt, err = db.PrepareContext(ctx, listCategories); err != nil {
		return nil, fmt.Errorf("error preparing query ListCategories: %w", err)
	}
	if q.listRecentTransactionsStmt, err = db.PrepareContext(ctx, listRecentTransactions); err != nil {
		return nil, fmt.Errorf("error preparing query ListRecentTransactions: %w", err)
	}
	if q.listTransactionsByYearStmt, err = db.PrepareContext(ctx, listTransactionsByYear); err != nil {
		return nil, fmt.Errorf("error preparing query ListTransactionsByYear: %w", err)
	}
	if q.listTransactionsByYearPaginatedStmt, err = db.PrepareContext(ctx, listTransactionsByYearPaginated); err != nil {
		return nil, fmt.Errorf("error preparing query ListTransactionsByYearPaginated: %w", err)
	}
	if q.listUsersStmt, err = db.PrepareContext(ctx, listUsers); err != nil {
		return nil, fmt.Errorf("error preparing query ListUsers: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.countAllTransactionsStmt != nil {
		if cerr := q.countAllTransactionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countAllTransactionsStmt: %w", cerr)
		}
	}
	if q.countTransactionsByYearStmt != nil {
		if cerr := q.countTransactionsByYearStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countTransactionsByYearStmt: %w", cerr)
		}
	}
	if q.createTransactionStmt != nil {
		if cerr := q.createTransactionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createTransactionStmt: %w", cerr)
		}
	}
	if q.deleteTransactionStmt != nil {
		if cerr := q.deleteTransactionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteTransactionStmt: %w", cerr)
		}
	}
	if q.getCategoryByNameStmt != nil {
		if cerr := q.getCategoryByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCategoryByNameStmt: %w", cerr)
		}
	}
	if q.getCategoryTotalsByYearStmt != nil {
		if cerr := q.getCategoryTotalsByYearStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCategoryTotalsByYearStmt: %w", cerr)
		}
	}
	if q.getDistinctTransactionYearsStmt != nil {
		if cerr := q.getDistinctTransactionYearsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDistinctTransactionYearsStmt: %w", cerr)
		}
	}
	if q.getMonthlyTotalsByYearStmt != nil {
		if cerr := q.getMonthlyTotalsByYearStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMonthlyTotalsByYearStmt: %w", cerr)
		}
	}
	if q.getUserStmt != nil {
		if cerr := q.getUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserStmt: %w", cerr)
		}
	}
	if q.listCategoriesStmt != nil {
		if cerr := q.listCategoriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listCategoriesStmt: %w", cerr)
		}
	}
	if q.listRecentTransactionsStmt != nil {
		if cerr := q.listRecentTransactionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listRecentTransactionsStmt: %w", cerr)
		}
	}
	if q.listTransactionsByYearStmt != nil {
		if cerr := q.listTransactionsByYearStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTransactionsByYearStmt: %w", cerr)
		}
	}
	if q.listTransactionsByYearPaginatedStmt != nil {
		if cerr := q.listTransactionsByYearPaginatedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTransactionsByYearPaginatedStmt: %w", cerr)
		}
	}
	if q.listUsersStmt != nil {
		if cerr := q.listUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUsersStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                  DBTX
	tx                                  *sql.Tx
	countAllTransactionsStmt            *sql.Stmt
	countTransactionsByYearStmt         *sql.Stmt
	createTransactionStmt               *sql.Stmt
	deleteTransactionStmt               *sql.Stmt
	getCategoryByNameStmt               *sql.Stmt
	getCategoryTotalsByYearStmt         *sql.Stmt
	getDistinctTransactionYearsStmt     *sql.Stmt
	getMonthlyTotalsByYearStmt          *sql.Stmt
	getUserStmt                         *sql.Stmt
	listCategoriesStmt                  *sql.Stmt
	listRecentTransactionsStmt          *sql.Stmt
	listTransactionsByYearStmt          *sql.Stmt
	listTransactionsByYearPaginatedStmt *sql.Stmt
	listUsersStmt                       *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                  tx,
		tx:                                  tx,
		countAllTransactionsStmt:            q.countAllTransactionsStmt,
		countTransactionsByYearStmt:         q.countTransactionsByYearStmt,
		createTransactionStmt:               q.createTransactionStmt,
		deleteTransactionStmt:               q.deleteTransactionStmt,
		getCategoryByNameStmt:               q.getCategoryByNameStmt,
		getCategoryTotalsByYearStmt:         q.getCategoryTotalsByYearStmt,
		getDistinctTransactionYearsStmt:     q.getDistinctTransactionYearsStmt,
		getMonthlyTotalsByYearStmt:          q.getMonthlyTotalsByYearStmt,
		getUserStmt:                         q.getUserStmt,
		listCategoriesStmt:                  q.listCategoriesStmt,
		listRecentTransactionsStmt:          q.listRecentTransactionsStmt,
		listTransactionsByYearStmt:          q.listTransactionsByYearStmt,
		listTransactionsByYearPaginatedStmt: q.listTransactionsByYearPaginatedStmt,
		listUsersStmt:                       q.listUsersStmt,
	}
}
