// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Category struct {
	ID    int64          `json:"id"`
	Name  string         `json:"name"`
	Type  string         `json:"type"`
	Icon  sql.NullString `json:"icon"`
	Color sql.NullString `json:"color"`
}

type Transaction struct {
	ID          int64        `json:"id"`
	UserID      int64        `json:"user_id"`
	CategoryID  int64        `json:"category_id"`
	Amount      int64        `json:"amount"`
	Currency    string       `json:"currency"`
	Description string       `json:"description"`
	Date        time.Time    `json:"date"`
	CreatedAt   sql.NullTime `json:"created_at"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
}

type User struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	Email     string       `json:"email"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type GdriveConfig struct {
	ID          int64          `json:"id"`
	Enabled     int64         `json:"enabled"`
	FolderID    sql.NullString `json:"folder_id"`
	FolderName  sql.NullString `json:"folder_name"`
	LastSyncAt  sql.NullTime   `json:"last_sync_at"`
	AutoBackup  int64         `json:"auto_backup"`
	CreatedAt   sql.NullTime  `json:"created_at"`
	UpdatedAt   sql.NullTime  `json:"updated_at"`
}

type BackupMetadata struct {
	ID            int64         `json:"id"`
	Version       string        `json:"version"`
	SchemaVersion int64         `json:"schema_version"`
	CreatedAt     sql.NullTime  `json:"created_at"`
	Checksum      sql.NullString `json:"checksum"`
}
