// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
  user_id, category_id, amount, currency, description, date
) VALUES (
  ?, ?, ?, ?, ?, ?
)
RETURNING id, user_id, category_id, amount, currency, description, date, created_at
`

type CreateTransactionParams struct {
	UserID      int64     `json:"user_id"`
	CategoryID  int64     `json:"category_id"`
	Amount      int64     `json:"amount"`
	Currency    string    `json:"currency"`
	Description string    `json:"description"`
	Date        time.Time `json:"date"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.queryRow(ctx, q.createTransactionStmt, createTransaction,
		arg.UserID,
		arg.CategoryID,
		arg.Amount,
		arg.Currency,
		arg.Description,
		arg.Date,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.Date,
		&i.CreatedAt,
	)
	return i, err
}

const getCategoryByName = `-- name: GetCategoryByName :one
SELECT id, name, type, icon, color FROM categories
WHERE name = ? LIMIT 1
`

func (q *Queries) GetCategoryByName(ctx context.Context, name string) (Category, error) {
	row := q.queryRow(ctx, q.getCategoryByNameStmt, getCategoryByName, name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Icon,
		&i.Color,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, name, email, created_at FROM users
WHERE id = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.queryRow(ctx, q.getUserStmt, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, type, icon, color FROM categories
ORDER BY type, name
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.query(ctx, q.listCategoriesStmt, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Icon,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentTransactions = `-- name: ListRecentTransactions :many
SELECT t.id, t.user_id, t.category_id, t.amount, t.currency, t.description, t.date, t.created_at, c.name as category_name, c.icon as category_icon, u.name as user_name
FROM transactions t
JOIN categories c ON t.category_id = c.id
JOIN users u ON t.user_id = u.id
ORDER BY t.date DESC
LIMIT 20
`

type ListRecentTransactionsRow struct {
	ID           int64          `json:"id"`
	UserID       int64          `json:"user_id"`
	CategoryID   int64          `json:"category_id"`
	Amount       int64          `json:"amount"`
	Currency     string         `json:"currency"`
	Description  string         `json:"description"`
	Date         time.Time      `json:"date"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	CategoryName string         `json:"category_name"`
	CategoryIcon sql.NullString `json:"category_icon"`
	UserName     string         `json:"user_name"`
}

func (q *Queries) ListRecentTransactions(ctx context.Context) ([]ListRecentTransactionsRow, error) {
	rows, err := q.query(ctx, q.listRecentTransactionsStmt, listRecentTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentTransactionsRow
	for rows.Next() {
		var i ListRecentTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.Date,
			&i.CreatedAt,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, created_at FROM users
ORDER BY name
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.query(ctx, q.listUsersStmt, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
