// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"time"
)

type Querier interface {
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) error
	GetCategoryByName(ctx context.Context, name string) (Category, error)
	GetCategoryStats(ctx context.Context, date time.Time) ([]GetCategoryStatsRow, error)
	GetUser(ctx context.Context, id int64) (User, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListRecentTransactions(ctx context.Context) ([]ListRecentTransactionsRow, error)
	ListUsers(ctx context.Context) ([]User, error)
}

var _ Querier = (*Queries)(nil)
