// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countAllTransactions = `-- name: CountAllTransactions :one
SELECT COUNT(*) as count FROM transactions
`

func (q *Queries) CountAllTransactions(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countAllTransactionsStmt, countAllTransactions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
  user_id, category_id, amount, currency, description, date
) VALUES (
  ?, ?, ?, ?, ?, ?
)
RETURNING id, user_id, category_id, amount, currency, description, date, created_at
`

type CreateTransactionParams struct {
	UserID      int64     `json:"user_id"`
	CategoryID  int64     `json:"category_id"`
	Amount      int64     `json:"amount"`
	Currency    string    `json:"currency"`
	Description string    `json:"description"`
	Date        time.Time `json:"date"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.queryRow(ctx, q.createTransactionStmt, createTransaction,
		arg.UserID,
		arg.CategoryID,
		arg.Amount,
		arg.Currency,
		arg.Description,
		arg.Date,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.Date,
		&i.CreatedAt,
	)
	return i, err
}

const getCategoryByName = `-- name: GetCategoryByName :one
SELECT id, name, type, icon, color FROM categories
WHERE name = ? LIMIT 1
`

func (q *Queries) GetCategoryByName(ctx context.Context, name string) (Category, error) {
	row := q.queryRow(ctx, q.getCategoryByNameStmt, getCategoryByName, name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Icon,
		&i.Color,
	)
	return i, err
}

const getCategoryTotalsByYear = `-- name: GetCategoryTotalsByYear :many
SELECT
    c.id as category_id,
    c.name as category_name,
    c.icon as category_icon,
    c.type as category_type,
    c.color as category_color,
    CAST(COALESCE(SUM(t.amount), 0) AS INTEGER) as total_amount,
    COUNT(t.id) as transaction_count
FROM categories c
LEFT JOIN transactions t ON t.category_id = c.id AND strftime('%Y', t.date) = CAST(? AS TEXT)
GROUP BY c.id, c.name, c.icon, c.type, c.color
ORDER BY c.type, total_amount DESC
`

type GetCategoryTotalsByYearRow struct {
	CategoryID       int64          `json:"category_id"`
	CategoryName     string         `json:"category_name"`
	CategoryIcon     sql.NullString `json:"category_icon"`
	CategoryType     string         `json:"category_type"`
	CategoryColor    sql.NullString `json:"category_color"`
	TotalAmount      int64          `json:"total_amount"`
	TransactionCount int64          `json:"transaction_count"`
}

func (q *Queries) GetCategoryTotalsByYear(ctx context.Context, dollar_1 string) ([]GetCategoryTotalsByYearRow, error) {
	rows, err := q.query(ctx, q.getCategoryTotalsByYearStmt, getCategoryTotalsByYear, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategoryTotalsByYearRow
	for rows.Next() {
		var i GetCategoryTotalsByYearRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.CategoryType,
			&i.CategoryColor,
			&i.TotalAmount,
			&i.TransactionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctTransactionYears = `-- name: GetDistinctTransactionYears :many
SELECT DISTINCT CAST(strftime('%Y', date) AS INTEGER) as year
FROM transactions
ORDER BY year DESC
`

func (q *Queries) GetDistinctTransactionYears(ctx context.Context) ([]int64, error) {
	rows, err := q.query(ctx, q.getDistinctTransactionYearsStmt, getDistinctTransactionYears)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var year int64
		if err := rows.Scan(&year); err != nil {
			return nil, err
		}
		items = append(items, year)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyTotalsByYear = `-- name: GetMonthlyTotalsByYear :many
SELECT
    CAST(strftime('%m', date) AS INTEGER) as month,
    c.type as category_type,
    CAST(COALESCE(SUM(amount), 0) AS INTEGER) as total_amount
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE strftime('%Y', t.date) = CAST(? AS TEXT)
GROUP BY month, c.type
ORDER BY month
`

type GetMonthlyTotalsByYearRow struct {
	Month        int64  `json:"month"`
	CategoryType string `json:"category_type"`
	TotalAmount  int64  `json:"total_amount"`
}

func (q *Queries) GetMonthlyTotalsByYear(ctx context.Context, dollar_1 string) ([]GetMonthlyTotalsByYearRow, error) {
	rows, err := q.query(ctx, q.getMonthlyTotalsByYearStmt, getMonthlyTotalsByYear, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMonthlyTotalsByYearRow
	for rows.Next() {
		var i GetMonthlyTotalsByYearRow
		if err := rows.Scan(&i.Month, &i.CategoryType, &i.TotalAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, name, email, created_at FROM users
WHERE id = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.queryRow(ctx, q.getUserStmt, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, type, icon, color FROM categories
ORDER BY type, name
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.query(ctx, q.listCategoriesStmt, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Icon,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentTransactions = `-- name: ListRecentTransactions :many
SELECT t.id, t.user_id, t.category_id, t.amount, t.currency, t.description, t.date, t.created_at, c.name as category_name, c.icon as category_icon, u.name as user_name
FROM transactions t
JOIN categories c ON t.category_id = c.id
JOIN users u ON t.user_id = u.id
ORDER BY t.date DESC
LIMIT 20
`

type ListRecentTransactionsRow struct {
	ID           int64          `json:"id"`
	UserID       int64          `json:"user_id"`
	CategoryID   int64          `json:"category_id"`
	Amount       int64          `json:"amount"`
	Currency     string         `json:"currency"`
	Description  string         `json:"description"`
	Date         time.Time      `json:"date"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	CategoryName string         `json:"category_name"`
	CategoryIcon sql.NullString `json:"category_icon"`
	UserName     string         `json:"user_name"`
}

func (q *Queries) ListRecentTransactions(ctx context.Context) ([]ListRecentTransactionsRow, error) {
	rows, err := q.query(ctx, q.listRecentTransactionsStmt, listRecentTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentTransactionsRow
	for rows.Next() {
		var i ListRecentTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.Date,
			&i.CreatedAt,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByYear = `-- name: ListTransactionsByYear :many
SELECT t.id, t.user_id, t.category_id, t.amount, t.currency, t.description, t.date, t.created_at, c.name as category_name, c.icon as category_icon, u.name as user_name
FROM transactions t
JOIN categories c ON t.category_id = c.id
JOIN users u ON t.user_id = u.id
WHERE strftime('%Y', t.date) = CAST(? AS TEXT)
ORDER BY t.date DESC
`

type ListTransactionsByYearRow struct {
	ID           int64          `json:"id"`
	UserID       int64          `json:"user_id"`
	CategoryID   int64          `json:"category_id"`
	Amount       int64          `json:"amount"`
	Currency     string         `json:"currency"`
	Description  string         `json:"description"`
	Date         time.Time      `json:"date"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	CategoryName string         `json:"category_name"`
	CategoryIcon sql.NullString `json:"category_icon"`
	UserName     string         `json:"user_name"`
}

func (q *Queries) ListTransactionsByYear(ctx context.Context, dollar_1 string) ([]ListTransactionsByYearRow, error) {
	rows, err := q.query(ctx, q.listTransactionsByYearStmt, listTransactionsByYear, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsByYearRow
	for rows.Next() {
		var i ListTransactionsByYearRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.Date,
			&i.CreatedAt,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countTransactionsByYear = `-- name: CountTransactionsByYear :one
SELECT COUNT(*) as count
FROM transactions t
WHERE strftime('%Y', t.date) = CAST(? AS TEXT)
`

func (q *Queries) CountTransactionsByYear(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.queryRow(ctx, q.countTransactionsByYearStmt, countTransactionsByYear, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listTransactionsByYearPaginated = `-- name: ListTransactionsByYearPaginated :many
SELECT t.id, t.user_id, t.category_id, t.amount, t.currency, t.description, t.date, t.created_at, c.name as category_name, c.icon as category_icon, c.type as category_type, u.name as user_name
FROM transactions t
JOIN categories c ON t.category_id = c.id
JOIN users u ON t.user_id = u.id
WHERE strftime('%Y', t.date) = CAST(? AS TEXT)
ORDER BY t.date DESC
LIMIT ? OFFSET ?
`

type ListTransactionsByYearPaginatedParams struct {
	Year   string
	Limit  int64
	Offset int64
}

type ListTransactionsByYearPaginatedRow struct {
	ID           int64          `json:"id"`
	UserID       int64          `json:"user_id"`
	CategoryID   int64          `json:"category_id"`
	Amount       int64          `json:"amount"`
	Currency     string         `json:"currency"`
	Description  string         `json:"description"`
	Date         time.Time      `json:"date"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	CategoryName string         `json:"category_name"`
	CategoryIcon sql.NullString `json:"category_icon"`
	CategoryType string         `json:"category_type"`
	UserName     string         `json:"user_name"`
}

func (q *Queries) ListTransactionsByYearPaginated(ctx context.Context, arg ListTransactionsByYearPaginatedParams) ([]ListTransactionsByYearPaginatedRow, error) {
	rows, err := q.query(ctx, q.listTransactionsByYearPaginatedStmt, listTransactionsByYearPaginated, arg.Year, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsByYearPaginatedRow
	for rows.Next() {
		var i ListTransactionsByYearPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.Date,
			&i.CreatedAt,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.CategoryType,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, created_at FROM users
ORDER BY name
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.query(ctx, q.listUsersStmt, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions
WHERE id = ? AND user_id = ?
`

type DeleteTransactionParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) error {
	_, err := q.exec(ctx, q.deleteTransactionStmt, deleteTransaction, arg.ID, arg.UserID)
	return err
}
