// Additional queries not generated by SQLC (manual addition for template compatibility)

package db

import (
	"context"
)

// GetDistinctTransactionYearsRow wraps year result for template compatibility
type GetDistinctTransactionYearsRow struct {
	Year int64 `json:"year"`
}

// GetDistinctTransactionYearsWrapped returns distinct years as structured rows
func (q *Queries) GetDistinctTransactionYearsWrapped(ctx context.Context) ([]GetDistinctTransactionYearsRow, error) {
	years, err := q.GetDistinctTransactionYears(ctx)
	if err != nil {
		return nil, err
	}
	var rows []GetDistinctTransactionYearsRow
	for _, y := range years {
		rows = append(rows, GetDistinctTransactionYearsRow{Year: y})
	}
	return rows, nil
}

// CountAllTransactions returns total number of transactions in the database
func (q *Queries) CountAllTransactions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, "SELECT COUNT(*) FROM transactions")
	var count int64
	err := row.Scan(&count)
	return count, err
}
